In [1]:
import numpy as np
def rot(a):
    return np.flip(a.T,0)
def a_print(A):
    for a in A:
        print(a)

In [2]:
print('A')
A=np.arange(6).reshape((3,2))
a_print(A)
print('B')
B=np.array([[0,1,5],[2,4,3]])
a_print(B)

A
[0 1]
[2 3]
[4 5]
B
[0 1 5]
[2 4 3]


In [3]:
from scipy.signal import convolve2d as conv

def comp(A,B):
    #pattern to search in both grids 
    pat = np.array([[1,10],[100,0]])
    
    pat=np.flip(np.flip(pat,axis=0),axis=1)
    sP = pat.shape
    sA = A.shape
    sB = B.shape
    Ai,Aj,Bk,Bl = np.nonzero(((conv(A,pat,mode='valid').reshape((1,-1))-conv(B,pat,mode='valid').reshape((-1,1)))==0).reshape((sA[0]-sP[0]+1,sA[1]-sP[1]+1,sB[0]-sP[0]+1,sB[1]-sP[1]+1)))
    for i,j,k,l in zip(Ai,Aj,Bk,Bl):
        print('A-embedding')
        dummyA = np.zeros((sA[0]+sB[0]-sP[0]+1,sA[1]+sB[1]-sP[1]+1))                
        dummyA[i:(i+sA[0]),j:(j+sA[1])]=A
        a_print(dummyA)
        print('B-embedding')
        dummyB = np.zeros((sA[0]+sB[0]-sP[0]+1,sA[1]+sB[1]-sP[1]+1))
        dummyB[k:(k+sB[0]),l:(l+sB[1])]=B
        a_print(dummyB)
        print('----------------------------')


In [4]:
for r in range(4):
    comp(A,B)
    B=rot(B)

A-embedding
[ 0.  1.  0.  0.]
[ 2.  3.  0.  0.]
[ 4.  5.  0.  0.]
[ 0.  0.  0.  0.]
B-embedding
[ 0.  1.  5.  0.]
[ 2.  4.  3.  0.]
[ 0.  0.  0.  0.]
[ 0.  0.  0.  0.]
----------------------------
